In [1]:
import pandas as pd
import numpy as np
import pycountry_convert as pyc

In [134]:
df_sui = pd.read_csv('master.csv')
df_sui = df_sui.drop(columns=['country-year', 'HDI for year'])
df_sui.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,"2,156,624,900",796,Boomers

In [130]:
df_ei = pd.read_csv('Education Index.csv', encoding= 'ISO-8859-1')
df_ei.dropna(axis=0, how='all')
df_ei.drop(df_ei.columns[df_ei.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
df_ei = df_ei.drop(['HDI Rank (2017)'], axis = 1)
df_ei.head()

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,0.122,0.133,0.145,0.156,0.168,0.179,0.190,0.202,0.213,...,0.347,0.359,0.371,0.382,0.390,0.398,0.406,0.410,0.410,0.415
1,Albania,0.584,0.589,0.558,0.543,0.542,0.551,0.558,0.571,0.580,...,0.646,0.652,0.673,0.693,0.730,0.732,0.733,0.733,0.742,0.745
2,Algeria,0.385,0.395,0.405,0.414,0.424,0.431,0.443,0.458,0.473,...,0.588,0.608,0.626,0.644,0.652,0.660,0.661,0.662,0.663,0.664
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.661,0.661,0.662,0.663,0.715,0.715,0.716,0.715,0.714,0.714
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.390,0.404,0.398,0.423,0.435,0.447,0.460,0.472,0.487,0.498

In [159]:
years = df_ei.columns[1:]
countries = df_ei.Country.unique()
df_ei_new = []

for country in countries:
    for year in  years:
        ei = df_ei[df_ei['Country']==country][year].values
        if len(ei) > 0: 
            item = {'country':str(country).strip(), 'year':np.int(year), 'educational Index':ei[0]}
        else:
            item = {'country':str(country).strip(), 'year':np.int(year), 'educational Index':""}
        df_ei_new.append(item)

df_ei_new = pd.DataFrame(df_ei_new)
df_ei_new.head()

       country educational Index  year
0  Afghanistan             0.122  1990
1  Afghanistan             0.133  1991
2  Afghanistan             0.145  1992
3  Afghanistan             0.156  1993
4  Afghanistan             0.168  1994

In [160]:
df_sui.merge(df_ei_new, on = ['country','year'])

,country,year,sex,age,suicides_no,population,suicides/100k pop,gdp_for_year ($),gdp_per_capita ($),generation,educational Index
0,Albania,1992,male,35-54 years,12,343800,3.49,"709,452,584",251,Boomers,0.558
1,Albania,1992,male,15-24 years,9,263700,3.41,"709,452,584",251,Generation X,0.558
2,Albania,1992,male,55-74 years,5,159500,3.13,"709,452,584",251,Silent,0.558
3,Albania,1992,male,25-34 years,7,245500,2.85,"709,452,584",251,Boomers,0.558
4,Albania,1992,female,15-24 years,7,292400,2.39,"709,452,584",251,Generation X,0.558
5,Albania,1992,female,25-34 years,4,267400,1.50,"709,452,584",251,Boomers,0.558
6,Albania,1992,female,35-54 years,2,323100,0.62,"709,452,584",251,Boomers,0.558
7,Albania,1992,female,55-74 years,1,164900,0.61,"709,452,584",251,Silent,0.558
8,Albania,1992,female,5-14 years,0,336700,0.00,"709,452,584",251,Millenials,0.558
9,Albania,1992,female,75+ years,0,38700,0.00,"709,452,584",251,G.I. Generation,0.558
10,Albania,1992,male,5-14 years,0,362900,0.00,"709,452,584",251,Millenials,0.558
11,Albania,1992,male,75+ years,0,23900,0.00,"709,452,584",251,G.I. Generation,0.558
12,Albania,1993,male,15-24 years,18,243300,7.40,"1,228,071,038",437,Generation X,0.543
13,Albania,1993,male,55-74 years,7,165000,4.24,"1,228,071,038",437,Silent,0.543
14,Albania,1993,male,75+ years,1,24200,4.13,"1,228,071,038",437,G.I. Generation,0.543
15,Albania,1993,male,25-34 years,9,230100,3.91,"1,228,071,038",437,Boomers,0.543
16,Albania,1993,female,15-24 years,10,285300,3.51,"1,228,071,038",437,Generation X,0.543
17,Albania,1993,male,35-54 years,10,350300,2.85,"1,228,071,038",437,Boomers,0.543
18,Albania,1993,female,25-34 years,7,261800,2.67,"1,228,071,038",437,Boomers,0.543
19,Albania,1993,female,35-54 years,7,331200,2.11,"1,228,071,038",437,Boomers,0.543
20,Albania,1993,female,55-74 years,2,169500,1.18,"1,228,071,038",437,Silent,0.543
21,Albania,1993,female,5-14 years,1,340300,0.29,"1,228,071,038",437,Millenials,0.543
22,Albania,1993,male,5-14 years,1,367000,0.27,"1,228,071,038",437,Millenials,0.543
23,Albania,1993,female,75+ years,0,39300,0.00,"1,228,071,038",437,G.I. Generation,0.543
24,Albania,1994,male,75+ years,2,24600,8.13,"1,985,673,798",697,G.I. Generation,0.542
25,Albania,1994,male,55-74 years,11,171400,6.42,"1,985,673,798",697,Silent,0.542
26,Albania,1994,female,75+ years,2,39900,5.01,"1,985,673,798",697,G.I. Generation,0.542
27,Albania,1994,male,25-34 years,6,231400,2.59,"1,985,673,798",697,Boomers,0.542
28,Albania,1994,male,35-54 years,9,362800,2.48,"1,985,673,798",697,Boomers,0.542
29,Albania,1994,male,15-24 years,6,242200,2.48,"1,985,673,798",697,Generation X,0.542
...,...,...,...,...,...,...,...,...,...,...,...
23352,Uzbekistan,2012,female,25-34 years,148,2556673,5.79,"51,821,573,338",1964,Millenials,0.692
23353,Uzbekistan,2012,female,35-54 years,89,3474788,2.56,"51,821,573,338",1964,Generation X,0.692
23354,Uzbekistan,2012,male,5-14 years,67,2701361,2.48,"51,821,573,338",1964,Generation Z,0.692
23355,Uzbekistan,2012,female,55-74 years,25,1283060,1.95,"51,821,573,338",1964,Boomers,0.692
23356,Uzbekistan,2012,female,75+ years,4,338557,1.18,"51,821,573,338",1964,Silent,0.692
23357,Uzbekistan,2012,female,5-14 years,16,2578408,0.62,"51,821,573,338",1964,Generation Z,0.692
23358,Uzbekistan,2013,male,35-54 years,481,3346411,14.37,"57,690,453,461",2150,Generation X,0.699
23359,Uzbekistan,2013,male,25-34 years,328,2644648,12.40,"57,690,453,461",2150,Millenials,0.699
23360,Uzbekistan,2013,female,15-24 years,323,3039740,10.63,"57,690,453,461",2150,Millenials,0.699
23361,Uzbekistan,2013,male,15-24 years,320,3171202,10.09,"57,690,453,461",2150,Millenials,0.699
23362,Uzbekistan,2013,male,55-74 years,119,1202790,9.89,"57,690,453,461",2150,Boomers,0.699
23363,Uzbekistan,2013,male,75+ years,13,221002,5.88,"57,690,453,461",2150,Silent,0.699
23364,Uzbekistan,2013,female,25-34 years,146,2647820,5.51,"57,690,453,461",2150,Millenials,0.699
23365,Uzbekistan,2013,female,35-54 years,99,3547895,2.79,"57,690,453,461",2150,Generation X,0.699
23366,Uzbekistan,2013,female,75+ years,8,345180,2.32,"57,690,453,461",2150,Silent,0.699
23367,Uzbekistan,2013,male,5-14 years,61,2720938,2.24,"57,690,453,461",2150,Generation Z,0.699
23368,Uzbekistan,2013,female,55-74 years,21,1356298,1.55,"57,690,453,461",2150,Boomers,0.699
23369,Uzbekistan,2013,female,5-14 years,31,2595000,1.19,"57,690,453,461",2150,Generation Z,0.699
23370,Uzbekistan,2014,male,35-54 years,519,3421300,15.17,"63,067,077,179",2309,Generation X,0.702
23371,Uzbekistan,2014,male,25-34 years,318,2739150,11.61,"63,067,077,179",2309,Millenials,0.702
23372,Uzbekistan,2014,female,15-24 years,347,2992817,11.59,"63,067,077,179",2309,Millenials,0.702
23373,Uzbekistan,2014,male,55-74 years,144,1271111,11.33,"63,067,077,179",2309,Boomers,0.702
23374,Uzbekistan,2014,male,15-24 years,347,3126905,11.10,"63,067,077,179",2309,Millenials,0.702
23375,Uzbekistan,2014,male,75+ years,17,224995,7.56,"63,067,077,179",2309,Silent,0.702
23376,Uzbekistan,2014,female,25-34 years,162,2735238,5.92,"63,067,077,179",2309,Millenials,0.702
23377,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,"63,067,077,179",2309,Generation X,0.702
23378,Uzbekistan,2014,female,75+ years,9,348465,2.58,"63,067,077,179",2309,Silent,0.702
23379,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,"63,067,077,179",2309,Generation Z,0.702
23380,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,"63,067,077,179",2309,Generation Z,0.702
23381,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,"63,067,077,179",2309,Boomers,0.702